# serverless.yml

service: rimss-be

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: server.server # reference the file and exported method
    timeout: 30
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true